Typo fixes
japandotorg/melon-docs pull request #11
Opened 2023-01-05 12:11 UTC by Saif-Discord

Fixed typos in the docs files, and a couple of brackets in the custom-commands file.

2023-01-05 12:18 UTC, ltzmax requested changes
while you're at this, could you also [change here](https://guide.melonbot.io/docs/utility/sticky/#syntax)? its using ` instead of > there.

2023-01-05 14:39 UTC, Saif-Discord commented
> while you're at this, could you also [change here](https://guide.melonbot.io/docs/utility/sticky/#syntax)? its using ` instead of > there.

Done, along with another minor fix.

2023-01-07 13:16 UTC, ltzmax requested changes

2023-01-07 13:16 UTC, ltzmax commented on docs/utility/sticky/sticky.mdx
>  **Toggle the header for stickied messages in this channel.**
This as well to match everything else.
```suggestion
Toggle the header for stickied messages in this channel.
```

2023-01-08 11:42 UTC, ltzmax approved these changes
Thanks. everything looks good. 
@japandotorg can merge when he got time and is around.

2023-01-28 16:29 UTC, japandotorg commented
Tysm for the pull request, appreciate much!!

2023-01-28 16:29 UTC, merged